author: e1abrador (Eric Labrador)
name: find_misconfigured_certificate_templates_esc1
state: enabled
tactic: privilege escalation
tag: attack
description: ESC1 occurs when a certificate template permits Client Authentication and allows the enrollee to supply an arbitrary Subject Alternative Name (SAN).
statement:
  main: >-
    match (ct:CertificateTemplate{domain:'RAS-DOMAIN', Enabled:true})
    where ct.`Enrollee Supplies Subject` = true and ct.`Client Authentication` = true
    return distinct ct.`Template Name` as `Template Name`, ct.`Client Authentication` as `Client Authentication`, ct.`Enrollee Supplies Subject` as `Enrollee Supplies Subject`
    order by `Client Authentication` desc, `Enrollee Supplies Subject` asc, `Template Name` asc
reference:
    - https://specterops.io/wp-content/uploads/sites/3/2022/06/Certified_Pre-Owned.pdf#page=58
    - https://github.com/ly4k/Certipy#esc1
    - https://research.ifcr.dk/certipy-2-0-bloodhound-new-escalations-shadow-credentials-golden-certificates-and-more-34d1c26f0dc6
    - https://specterops.io/wp-content/uploads/sites/3/2022/06/Certified_Pre-Owned.pdf#page=106
    - https://specterops.io/wp-content/uploads/sites/3/2022/06/Certified_Pre-Owned.pdf#page=114
    - https://specterops.io/wp-content/uploads/sites/3/2022/06/Certified_Pre-Owned.pdf#page=119
    - https://specterops.io/wp-content/uploads/sites/3/2022/06/Certified_Pre-Owned.pdf#page=125
nextsteps:
    rt:
      - Misconfigured Certificate Templates - ESC1
    bt:
      - Harden Certificate Template Settings - PREVENT4
      - Enforce Strict User Mappings - PREVENT7
      - Monitor User/Machine Certificate Enrollments - DETECT1
      - Monitor Certificate Authentication Events - DETECT2
