author: e1abrador (Eric Labrador)
name: find_all_misconfigured_templates_esc3
state: enabled
tactic: collection
tag: analysis
description: ESC3 occur when a certificate template specifies the Certificate Request Agent EKU (Enrollment Agent). This EKU can be used to request certificates on behalf of other users.
statement:
  main: >-
     MATCH (n:CertificateTemplate{domain:'RAS-DOMAIN'})
     WHERE n.`Enrollment Agent` = true 
     RETURN n.`Template Name` AS `Template Name`, n.Enabled AS `Template Enabled`, n.`highvalue` AS `High Value Target`, n.`Client Authentication` AS `Client Authentication`, n.`Enrollment Agent` AS `Enrollment Agent`, n.`Enrollee Supplies Subject` AS `Enrollee Supplies Subject`
     ORDER BY `Template Name` ASC
reference:
  - https://github.com/ly4k/Certipy#esc3
  - https://specterops.io/wp-content/uploads/sites/3/2022/06/Certified_Pre-Owned.pdf#page=66&zoom=100,93,345
  - https://specterops.io/wp-content/uploads/sites/3/2022/06/Certified_Pre-Owned.pdf#page=101&zoom=100,93,469
  - https://specterops.io/wp-content/uploads/sites/3/2022/06/Certified_Pre-Owned.pdf#page=106&zoom=100,93,374
  - https://research.ifcr.dk/certipy-2-0-bloodhound-new-escalations-shadow-credentials-golden-certificates-and-more-34d1c26f0dc6
nextsteps:
    rt:
      - Request a certificate based on the vulnerable certificate template. Try to request a certificate for a domain administrator.
    bt:
      - If the template does not actually require SAN specification, the first option is to remove the “Supply in Request” setting under the “Subject Name” settings for any affected template (this will disable the CT_FLAG_ENROLLEE_SUPPLIES_SUBJECT flag).
      - Enable certificate approvals on the template.
      - Configure authorized signatures to enact CSR signing restrictions for the template.
